@hostname = localhost
@port = 3001
@host = http://{{hostname}}:{{port}}

POST {{host}}/phonebook/ HTTP/1.1
Accept: application/json
Content-Type: application/json
//garder  et espace obliger 

{
  "name": "MMMMM HATE U",
  "number": "54646"
}

